# -*- coding: utf-8 -*-
"""Python Auction Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DF-DgjQm2-nKZjPwMW95xqiu78KRa6cA
"""

#def Auction Project
def auction_program():
  print("Welcome to the auction program!")

  item = input("Enter the name of the item you want to auction: ")
  print(f"You are bidding on {item}")

  winner_name = None
  winner_bid = 0

  while True:
    name = input("Enter your name: ")
    bid = int(input("Enter your bid amout: "))

    if bid > winner_bid:
      winner_name = name
      winner_bid = bid
      print("Congraulations! You are now the highest bidder!")

    end_auction = input ("Do you want to end the auction? (yes/no)")
    if end_auction.lower() == "yes":
      break

  print("The Auction Has Closed")
  if winner_name:
    print(f"{winner_name} won the auction with a bid of ${winner_bid}")
  else:
    print("No bids were placed.")
  print("Thank you for using the auction program!")

auction_program()